# Generated by Django 5.0.6 on 2025-12-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_alter_misc_key_alter_scheduleentry_event_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(default='@amb.sch.ae', max_length=254)),
                ('about', models.TextField()),
                ('photo', models.ImageField(upload_to='chair_photos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='committee',
            name='chair_1_id',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='chair_2_id',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='chair_3_id',
        ),
        migrations.AddField(
            model_name='committee',
            name='chairs',
            field=models.ManyToManyField(related_name='chairs', to='website.chair'),
        ),
        migrations.AlterField(
            model_name='misc',
            name='Key',
            field=models.CharField(default='382949', max_length=1000, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='committee',
            name='pagers',
            field=models.ManyToManyField(related_name='pagers', to='website.pager'),
        ),
    ]
