# Generated by Django 5.0.6 on 2025-12-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_pager_remove_committee_chair_1_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='pagers',
            field=models.ManyToManyField(blank=True, related_name='pagers', to='website.pager'),
        ),
        migrations.AlterField(
            model_name='misc',
            name='Key',
            field=models.CharField(default='606095', max_length=1000, primary_key=True, serialize=False),
        ),
    ]
