# Generated by Django 5.0.6 on 2025-12-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_alter_committee_pagers_alter_misc_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chair',
            name='email',
            field=models.CharField(default='+971 00 000 0000', max_length=16),
        ),
        migrations.AlterField(
            model_name='misc',
            name='Key',
            field=models.CharField(default='131217', max_length=1000, primary_key=True, serialize=False),
        ),
    ]
