# Generated by Django 5.0.6 on 2025-12-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_alter_chair_email_alter_misc_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chair',
            name='email',
            field=models.EmailField(default='@amb.sch.ae', max_length=254),
        ),
        migrations.AlterField(
            model_name='misc',
            name='Key',
            field=models.CharField(default='322712', max_length=1000, primary_key=True, serialize=False),
        ),
    ]
